apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-web-app
  name: my-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-web-app-exposed
  template:
    metadata:
      labels:
        run: my-web-app-exposed
    spec:
      containers:
        - name: my-web-app
          image: localhost:5000/my-web-app:2.0
          ports:
            - containerPort: 80

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-web-app
  name: my-web-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-web-app-exposed
  type: NodePort